Repository Qiskit/ecosystem, pull requests merged in 2021-09, with the labels that each got.

#24 Workflow: tests on pr
  .github/workflows/tests.yml
Labels: bug

#25 Workflow: manual dispatch for test workflow
  .github/workflows/tests.yml
Labels: enhancement

#8 Configuration for ecosystem members
  .github/workflows/check-main-repos.yml
  .github/workflows/tests.yml
  CONTRIBUTING.md
  docs/dev/dev-doc.md
  ecosystem/commands.py
  ecosystem/controller.py
  ecosystem/controllers/__init__.py
  ecosystem/controllers/runner.py
  ecosystem/entities.py
  ecosystem/manager.py
  ecosystem/models/__init__.py
  ecosystem/models/configuration.py
  ecosystem/resources/members.json
  ecosystem/templates/configured_tox.ini
  ecosystem/utils.py
  tests/common.py
  tests/resources/configured_python_repository/qe_config.json
  tests/resources/configured_python_repository/qlib/__init__.py
  tests/resources/configured_python_repository/qlib/impl.py
  tests/resources/configured_python_repository/requirements-dev.txt
  tests/resources/configured_python_repository/requirements.txt
  tests/resources/configured_python_repository/setup.cfg
  tests/resources/configured_python_repository/setup.py
  tests/resources/configured_python_repository/tests/__init__.py
  tests/resources/configured_python_repository/tests/test_impl.py
  tests/resources/simple_python_repository/qlib/__init__.py
  tests/resources/simple_python_repository/qlib/impl.py
  tests/resources/simple_python_repository/requirements.txt
  tests/resources/simple_python_repository/setup.cfg
  tests/resources/simple_python_repository/setup.py
  tests/resources/simple_python_repository/tests/__init__.py
  tests/resources/simple_python_repository/tests/test_impl.py
  tests/test_commands.py
  tests/test_configuration.py
  tests/test_controller.py
  tests/test_entities.py
  tests/test_runner.py
Labels: documentation, enhancement

#22 Submission: implement python parser for template
  .pylintrc
  ecosystem/entities.py
  ecosystem/manager.py
  tests/ressources/issue.md
  tests/test_manager.py
Labels: enhancement

#28 Make only 1 resources directory
  tests/resources/issue.md
  tests/test_manager.py
Labels: bug

#32 Commands: refactor commands in classes
  ecosystem/commands/__init__.py
  ecosystem/commands/command.py
  ecosystem/runners/python_styles_runner.py
  ecosystem/runners/python_tests_runner.py
  ecosystem/runners/runner.py
  tests/commands/test_commands.py
Labels: enhancement, QAMP fall 2021

#33 CI: coverage and black jobs in tests workflow
  .coveragerc
  .github/workflows/tests.yml
  ecosystem/commands/__init__.py
  ecosystem/commands/command.py
  ecosystem/daos/jsondao.py
  ecosystem/manager.py
  ecosystem/models/configuration.py
  ecosystem/models/execution_summary.py
  ecosystem/models/repository.py
  ecosystem/models/test_results.py
  ecosystem/models/test_type.py
  ecosystem/models/tier.py
  ecosystem/runners/python_styles_runner.py
  ecosystem/runners/python_tests_runner.py
  ecosystem/runners/runner.py
  ecosystem/templates/__init__.py
  ecosystem/utils/submission_parser.py
  ecosystem/utils/utils.py
  requirements-dev.txt
  tests/commands/test_commands.py
  tests/common.py
  tests/daos/test_dao.py
  tests/models/test_configuration.py
  tests/models/test_repository.py
  tests/resources/configured_python_repository/qlib/impl.py
  tests/resources/configured_python_repository/setup.py
  tests/resources/simple_python_repository/qlib/impl.py
  tests/resources/simple_python_repository/setup.py
  tests/runners/test_runner.py
  tests/utils/test_utils.py
  tox.ini
Labels: enhancement, QAMP fall 2021

#40 Issue 38 | CRUD for json dao
  ecosystem/daos/jsondao.py
  ecosystem/manager.py
  tests/daos/test_dao.py
Labels: enhancement, QAMP fall 2021

#43 Issue #41 | CI: parameteric tests action
  .github/actions/run-tests/action.yml
  .github/workflows/style-check.yml
  ecosystem/manager.py
Labels: enhancement, QAMP fall 2021
