Repository Qiskit/ecosystem, pull requests merged in 2022-09, with the labels that each got.

#207 Added Qiskit Experiments
  README.md
  ecosystem/resources/members.json
Labels: member

#216 Issue 200 | PyEPR skip tests
  ecosystem/resources/members.json
Labels: enhancement

#219 Fix tiers
  ecosystem/resources/members.json
Labels: bug

#225 Issue 155 | Force update qiskit version for stable tests
  ecosystem/manager.py
Labels: bug

#226 Issue 188 | Run each type of tests as separate workflow
  .github/actions/run-tests/action.yml
  .github/workflows/ecosystem-project-check.yml
  .github/workflows/test_payloads/project-check-payload.json
  ecosystem/manager.py
Labels: enhancement
